### ISSUE TITLE
THREE.WebGLProgram: Shader Error 1282 - VALIDATE_STATUS false

### ISSUE THREAD

**Issue by ashconnell** [StrandedKitty/three-csm#17]
The current npm version of three-csm (1.1.1) doesn't seem to work with the current version of three (0.135.0).

It was spitting out errors about the shader: 

```
THREE.WebGLProgram: Shader Error 1282 - VALIDATE_STATUS false
```

After switching my import from `three-csm` to use the official examples, `three/examples/jsm/csm/CSM.js`, it started working!

I suspect this repo lags behind three? 

Anyway, i'm mostly just posting this in case someone else gets stuck :)

Awesome shadows btw :D

**Comment by StanislavChankov** [comment]
I have the same issue.

The right way to import the library is: `import { default as CSM } from 'three-csm';`

**Comment by kriffe** [comment]
Similar error here. The shader (among other things) seems to have been updated a few times.

Some of the diffs in Shader.js and CSMShader.js in threejs examples
![image](https://user-images.githubusercontent.com/10418534/183875103-0285b5fc-6025-44ff-80c7-5f9ba799ed7c.png)

![image](https://user-images.githubusercontent.com/10418534/183875221-f69b97b8-bc3b-43d2-8e14-451bcc3401bc.png)

![image](https://user-images.githubusercontent.com/10418534/183875428-bd2d32cd-2806-44d4-8657-7fd26b0a19b6.png)

Would be nice if this repo could be used instead of the examples in threejs

**Comment by StrandedKitty** [comment]
Hi, you are right, this repo lags behind three.js examples, I don't update in often enough. But it only matters for new three.js versions.

I will update this repo and package soon (I hope this week), thanks.

**Comment by StrandedKitty** [comment]
I've updated this repo to match the implementation from three.js examples. Current package version - v2.0.0.
